### ISSUE TITLE
add public-facing descriptions next to file names

### ISSUE THREAD

**Issue by anjunainaustin** [18F/arl-oss-process#10]
Right now, next to file names is text that looks like it's notes for the internal team ("add presentation title". Is there a way to remove this and/or replace it with some sort of description to give file's context. Right now, I think someone seeing the Product Ownership file would be very confused.

**Comment by adunkman** [comment]
The content next to file names is the commit message — it’s a standard source control thing, which is a summary of the changes. GitHub shows this message next to files, which corresponds to the timestamp in the right column. 

We’re a little limited on this section of the file displays; you can see similar messages on other Path Analysis repos like [18F/afrs-pa](https://github.com/18F/afrs-pa) and [18F/usda-snap-pa](https://github.com/18F/usda-snap-pa). 

However, we can add a README to each of those folders, which would let us show additional content beneath the list of files — where we could describe the contents further.
